[package]
name = "gost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
primitive-types = "0.12.2"
sha1 = "0.10.6"